basePath: /
host: picpay-loan-sre-interview-challenge.ms.qa
info:
  contact:
    name: 'group:default/squad-sre-emprestimo'
    url: https://picpay.atlassian.net/jira/software/c/projects/SC1SRE/boards/3064
  description: Desafio SRE Empréstimos
  termsOfService: http://swagger.io/terms/
  title: picpay-loan-sre-interview-challenge
  version: "1.0"
paths:
  /health:
    get:
      consumes:
        - '*/*'
      description: get the status of server.
      produces:
        - application/json
      responses:
        "200":
          description: OK
          schema:
            additionalProperties: true
            type: object
      summary: Show the status of server.
      tags:
        - root
swagger: "2.0"
